name: .NET Build and Test

on:
  pull_request:
    branches: [ "main" ]
  push:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.303

    - name: Restore all projects
      run: dotnet restore

    - name: Install required workloads
      run: dotnet workload restore

    - name: Build all projects
      run: dotnet build --configuration Release --no-restore

    - name: Test all projects
      run: dotnet test --no-build --configuration Release --verbosity detailed
